import {
  generateArchitectureDoc,
  generateMermaidDiagram,
  serializeForgeConfig,
  resolveBackendDependencies,
  resolveFrontendDependencies,
  type ForgeConfig,
} from '@forgestack/core';
import type { GeneratedFile } from '../types.js';

export function generateDocsAndConfigs(config: ForgeConfig, isMonorepo: boolean): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // 1. forge.config.yaml (Canonical single source of truth!)
  files.push({
    path: 'forge.config.yaml',
    content: serializeForgeConfig(config),
  });

  // 2. ARCHITECTURE.md
  files.push({
    path: 'ARCHITECTURE.md',
    content: generateArchitectureDoc(config),
  });

  // 3. architecture.mmd (Pure mermaid file)
  files.push({
    path: 'architecture.mmd',
    content: generateMermaidDiagram(config),
  });

  // 4. .env.example
  const envLines: string[] = [
    '# =============================================================================',
    '# Environment Variables Template - Generated by ForgeStack',
    '# Copy this file to .env and configure your secrets.',
    '# =============================================================================',
    '',
  ];

  if (config.backend && config.backend.framework !== 'none') {
    const beManifest = resolveBackendDependencies(config);
    envLines.push('# Backend Configuration');
    for (const [key, details] of Object.entries(beManifest.envVariables)) {
      envLines.push(`# ${details.description} (Required: ${details.required})`);
      envLines.push(`${key}=${details.defaultValue || ''}`);
      envLines.push('');
    }
  }

  if (config.frontend && config.frontend.framework !== 'none') {
    const feManifest = resolveFrontendDependencies(config);
    envLines.push('# Frontend Configuration');
    for (const [key, details] of Object.entries(feManifest.envVariables)) {
      envLines.push(`# ${details.description} (Required: ${details.required})`);
      envLines.push(`${key}=${details.defaultValue || ''}`);
      envLines.push('');
    }
  }

  files.push({
    path: '.env.example',
    content: envLines.join('\n'),
  });

  // 5. README.md
  const readme = `# ${config.project.name}

> Generated by **[ForgeStack](https://github.com/Sanskar225/forgestack)** — Architecture-aware application generator.

## 🚀 Quick Start

### 1. Configure Environment
\`\`\`bash
cp .env.example .env
\`\`\`

### 2. Start Services with Docker Compose
\`\`\`bash
docker compose up -d
\`\`\`

### 3. Run Development Server
\`\`\`bash
npm run dev
\`\`\`

---

## 🛠️ Architecture Management with \`forge\` CLI

This project includes the **ForgeStack local CLI** for ongoing architecture management:

- \`npx forge doctor\` — Verify runtime and container health
- \`npx forge validate\` — Validate \`forge.config.yaml\` architecture rules
- \`npx forge visualize\` — Display ASCII architecture diagram and refresh \`ARCHITECTURE.md\`
- \`npx forge add <module>\` — Dynamically inject services (e.g. \`npx forge add redis\`)
- \`npx forge generate\` — Resynchronize files against \`forge.config.yaml\`
- \`npx forge diff\` — Check for architectural drift

See [ARCHITECTURE.md](./ARCHITECTURE.md) for full architectural specifications and topology diagrams.
`;

  files.push({
    path: 'README.md',
    content: readme,
  });

  return files;
}
